### ISSUE TITLE
Replace não esta funcionando quando e repassado um intero

### ISSUE THREAD

**Issue by HerdesonMourao** [HerdesonMourao/authenticate-docs#4]

**Comment by HerdesonMourao** [comment]
```
/home/herdeson/Development/Scripts/teste/node_modules/authenticate-docs/src/index.js:11
    cpf = cpf.replace(/\./g, '');
              ^

TypeError: cpf.replace is not a function
    at validateCPF (/home/herdeson/Development/Scripts/teste/node_modules/authenticate-docs/src/index.js:11:15)
    at Object.<anonymous> (/home/herdeson/Development/Scripts/teste/indes.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```
